FORMAT: 1A
HOST: http://xo-signin.herokuapp.com/

# xo-signing

xo-signin is a simple web api allowing user registration with e-mail verification, password and username
recovery.

## Signup resource [/signup]

### Register new user [POST]

Registers a new user. Asks for e-mail verification.
The 409 response is returned if a user with a given e-mail address or username already exists.
Following Attributes used:

+ email (string) - The e-mail address provided by user.
+ username (string) - Unique user identifier chosen by user. 
+ password (string) - The password used to authenticate the user.

+ Request (application/json)

            {
                "email" : "mtari11@freeuni.edu.ge",
                "username" : "MT13",
                "password" : "1234"
            }

+ Response 200 (application/json)

            {
                "email" : "mtari11@freeuni.edu.ge",
                "username" : "MT13"
            }

+ Response 409 (application/json)

            {
                "username_error" : false,
                "email_error" : true,
            }

## E-mail adress confirmation resource [/confirm_email/{token}]

### Confirm e-mail address [GET]
Confirms e-mail address to complete user registration process.
+ Parameters
    + token (required, string, `0b3211d3-76c6-456d-8971-20aa277bfc76`)

+ Response 200 (application/json)

            {
                "email" : "mtari11@freeuni.edu.ge",
                "username" : "MT13"
            }

+ Response 404 (application/json)

## Password recovery resource [/recover_password]

### Request password recovery via e-mail [POST]

Allows user to request new password in case it was forgotten.

+ Request (application/json)

        {
            "email"  :"mtari11@freeuni.edu.ge",
            "username" : "MT13"
        }

+ Response 200

+ Response 401


## E-mail password recovery resource [/recover_password/{token}]

### Recover/change password from email [POST]

Allows user to choose new password in case it was forgotten. This URI is supposed to be invoked from e-mail.

+ Parameters
    + token (required, string, `0b3211d3-76c6-456d-8971-20aa277bfc76`)

+ Request (application/json)

            { 
                "password" : "1234"
            }

+ Response 200

+ Response 404

## Username recovery resource [/recover_username]

### Recover username [POST]

Allows user to be reminded of his/her username via e-mail message. On success, e-mail message with username is sent.

+ Request (application/json)

            { 
                "email" : "mtari11@freeuni.edu.ge"
            }

+ Response 200

+ Response 401
