FORMAT: 1A
HOST: http://xo-game-sdp.herokuapp.com/webapi

# xo-signing

xo-signin is a simple web api allowing user registration with e-mail verification, password and username
recovery.

# xo-signin API Root [/]

## Register new user [POST/signup]

Registers a new user. Asks for e-mail verification.

Attributes used:

email    - The e-mail address provided by user.
username - Unique user identifier provided by user. 
password - The password used to authenticate the user.

The 409 response is returned if a user with a given e-mail address or username already exists.

+ Request (application/json)

            { 
                "email" : "mtari11@freeuni.edu.ge",
                "username" : "MT13",
                "password" : "1234"
            }

+ Response 200 (application/json)

            {
                "id" : "222",
                "email" : "mtari11@freeuni.edu.ge",
                "username" : "MT13"
            }

+ Response 409

            {
                "username_exists" : false,
                "email_used" : true,
                "message" : "The email address mtari11@freeuni.edu.ge is already registered. Please try different email address."
            }
            
## Confirm e-mail address [POST/confirm_email/{token}]

Confirms e-mail address to complete user registration process.

+ Parameters
    + token (required, string, `"0b3211d3-76c6-456d-8971-20aa277bfc76"`)

+ Response 200 (application/json)

                {
                    "id" : "222",
                    "email" : "mtari11@freeuni.edu.ge",
                    "username" : "MT13"
                }

+ Response 404 (application/json)

## Password recovery [POST/recover_password]

This resource is in head of password recovery.

+ Request (application/json)

        { 
            "email" : "mtari11@freeuni.edu.ge"
            "username" : "MT13"
        }

+ Response 200 (application/json)

        { 
            "success": true,
            "message": "reset instructions have been sent"
        }

+ Response 401 (application/json)

        { 
            "success": false,
            "message": "the email address or username was not found" 
        }

## Password recovery from email [POST/recover_password/{token}]

Allows user to change forgotten password.

+ Parameters
    + token (required, string, `"0b3211d3-76c6-456d-8971-20aa277bfc76"`)

+ Request (application/json)

            { 
                "password" : "1234"
            }

+ Response 200 (application/json)

+ Response 404 (application/json)

## Username recovery [POST/recover_username]

This resource is in head of username recovery.

+ Request (application/json)

        { 
            "email" : "mtari11@freeuni.edu.ge"
        }

+ Response 200 (application/json)

        { 
            "success": true,
            "message": "username was sent to e-mail address."
        }

+ Response 401 (application/json)

        { 
            "success": false,
            "message": "the e-mail address was not found" 
        }
